# Generated by Django 3.0.6 on 2020-05-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=200)),
                ('user_lname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_color', models.CharField(max_length=200)),
                ('note_card_width', models.CharField(max_length=200)),
                ('note_card_height', models.CharField(max_length=200)),
                ('note_title', models.CharField(max_length=200)),
                ('note_text', models.CharField(max_length=200)),
                ('note_position', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.User')),
            ],
        ),
    ]
